### ISSUE TITLE
can't see REVERSED label

### ISSUE THREAD

**Issue by eostrom** [jlooper/nsvue-workshop#2]
Even when the icons are reversed, I never see a label that says REVERSED.

I noticed there's no `reversed` property in the `data` object, so I added that, but I still don't see it.

Aha! I think I found it but I'm not sure what the appropriate fix is. The `.status` selector has a `margin: -30`, which (on my Pixel 2) seems to position it somewhere outside the `StackLayout`.

**Comment by jlooper** [comment]
oh, I see the same thing on Android. Let me dig a bit, thanks for the heads up!

**Comment by jlooper** [comment]
yep, that's the issue. I'll get rid of that, and it is fine on iOS and Android. Wonder why I stuck that in there? 🤔

**Comment by jlooper** [comment]
fixed in codebase, playground demo, and instructions, thank you!
